spring.application.name=${SPRING_APPLICATION_NAME:projeto-pdm-artesao-api}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projeto_pdm_artesao_api}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.jpa.hibernate.ddl-auto=update

# this is test only:
jwt.secret=s0dqtPE4pK271ZbTX8hjYoYoY7T7f31eTqNeYaBAPKx
jwt.expiration=${JWT_EXPIRATION:86400000}

server.port=8080
server.address=0.0.0.0
